apiVersion: v1
kind: Namespace
metadata:
  name: vault-bank-staging
  labels:
    app.kubernetes.io/name: vault-bank
    app.kubernetes.io/part-of: vault-bank
    application: vault-bank
    environment: staging
