apiVersion: v1
kind: ResourceQuota
metadata:
  name: vaultbank-staging-free-tier-quota
spec:
  hard:
    requests.cpu: "1200m"
    requests.memory: 2600Mi
    limits.cpu: "3500m"
    limits.memory: 4500Mi
    requests.storage: 20Gi
    persistentvolumeclaims: "10"
    pods: "30"
