sonar.projectKey=vault-bank
sonar.projectName=Vault Bank
sonar.sourceEncoding=UTF-8
sonar.sources=backend-service/apps,backend-service/libs,frontend/src
sonar.tests=backend-service/apps,backend-service/libs
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.module.ts,**/reports/**
sonar.javascript.lcov.reportPaths=backend-service/coverage/lcov.info
