sonar.projectKey=sonappatil_vault_bank
sonar.organization=sonappatil
sonar.projectName=Vault Bank
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=backend-service/apps,backend-service/libs,frontend/src

sonar.tests=backend-service/apps,backend-service/libs
sonar.test.inclusions=backend-service/apps/**/*.spec.ts,backend-service/libs/**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/reports/**,**/*.spec.ts,**/*.module.ts,**/main.ts,**/data-source.ts,**/migrations/**

sonar.javascript.lcov.reportPaths=backend-service/coverage/lcov.info

sonar.scm.provider=git
sonar.links.scm=https://github.com/sonappatil/vault_bank
sonar.links.ci=https://github.com/sonappatil/vault_bank
