apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-runtime-config
data:
  APP_RUNTIME: kubernetes
  NODE_ENV: production
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
  VAULT_REWRITE_DOCKER_URLS_FOR_HOST: "false"
  DATABASE_SSL: "true"
  AUTH_SERVICE_URL: http://auth-service:3001/v1
  ACCOUNT_SERVICE_URL: http://account-service:3002/v1
  TRANSACTION_SERVICE_URL: http://transaction-service:3003/v1
  PAYMENT_SERVICE_URL: http://payment-service:3004/v1
  RECEIPT_BASE_URL: https://receipts.example.com
  PAYPAL_API_URL: https://api-m.sandbox.paypal.com
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "465"
  SMTP_SECURE: "true"
  PAYMENT_OTP_CHANNEL: sms
  PAYMENT_OTP_EMAIL_FALLBACK: "true"
  BANK_CODE: "10"
