apiVersion: v1
kind: ResourceQuota
metadata:
  name: vaultbank-prod-free-tier-quota
spec:
  hard:
    requests.cpu: "900m"
    requests.memory: 1800Mi
    limits.cpu: "2200m"
    limits.memory: 3200Mi
    pods: "20"
