apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-bank-runtime
  labels:
    app.kubernetes.io/name: vault-bank-runtime
    app.kubernetes.io/part-of: vault-bank
    application: vault-bank
    environment: production
automountServiceAccountToken: false
imagePullSecrets:
  - name: harbor-vault-bank-pull
