FROM node:22-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

FROM dependencies AS migrator
WORKDIR /app
ENV NODE_ENV=production
COPY tsconfig.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs
USER node
CMD ["npm", "run", "migration:run:all"]
