listeners.tcp.default = 5672
management.tcp.port = 15672

loopback_users.guest = false
heartbeat = 60
channel_max = 2048
consumer_timeout = 1800000

vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB

default_queue_type = quorum
management.load_definitions = /etc/rabbitmq/definitions.json
