apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-service-allow-traefik-and-vaultbank
  namespace: vault-bank-prod
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: vaultbank
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: vaultbank
      ports:
        - protocol: TCP
          port: 3001
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: account-service-allow-traefik-and-vaultbank
  namespace: vault-bank-prod
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/part-of: vaultbank
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: account-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: vaultbank
      ports:
        - protocol: TCP
          port: 3002
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transaction-service-allow-traefik-and-vaultbank
  namespace: vault-bank-prod
  labels:
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/part-of: vaultbank
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: transaction-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: vaultbank
      ports:
        - protocol: TCP
          port: 3003
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-service-allow-traefik-and-vaultbank
  namespace: vault-bank-prod
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: vaultbank
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: payment-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: vaultbank
      ports:
        - protocol: TCP
          port: 3004
