apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-bank-staging

resources:
  - runtime.yaml

configMapGenerator:
  - name: postgres-bootstrap
    files:
      - postgres-init.sh=config/postgres/init.sh
      - postgres-init.sql=config/postgres/init.sql

  - name: redis-config
    files:
      - redis.conf=config/redis/redis.conf

  - name: rabbitmq-config
    files:
      - rabbitmq.conf=config/rabbitmq/rabbitmq.conf
      - definitions.template.json=config/rabbitmq/definitions.json
      - docker-entrypoint-custom.sh=config/rabbitmq/entrypoint.sh
