apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-bank-staging

resources:
  - runtime.yaml

configMapGenerator:
  - name: postgres-bootstrap
    files:
      - postgres-init.sh=config/postgres/init.sh
      - postgres-init.sql=config/postgres/init.sql

  - name: redis-config
    files:
      - redis.conf=config/redis/redis.conf

  - name: rabbitmq-config
    files:
      - rabbitmq.conf=config/rabbitmq/rabbitmq.conf
      - definitions.template.json=config/rabbitmq/definitions.json
      - docker-entrypoint-custom.sh=config/rabbitmq/entrypoint.sh

images:
  - name: postgres-runtime
    newName: harbor.vaultbank.internal:9443/vault-bank/postgres-runtime
    digest: sha256:2cd1d58a4f07c0895efcfe22826e63fdace4a093ae9174131b8b827b9a45749a

  - name: redis-runtime
    newName: harbor.vaultbank.internal:9443/vault-bank/redis-runtime
    digest: sha256:58114ad49688e1bbfc1987829eae6be8446f5b608f0c9652af4a3a94833d551c

  - name: rabbitmq-runtime
    newName: harbor.vaultbank.internal:9443/vault-bank/rabbitmq-runtime
    digest: sha256:39f934e10a7b95179171a70f15f02636201a153a2c689e961fc0f445bac275f2
