FROM alpine:3.19 AS cert-gen

RUN apk add --no-cache openssl

ARG NGINX_HOST=localhost
ENV NGINX_HOST=${NGINX_HOST}

COPY scripts/generate-certs.sh /usr/local/bin/generate-certs.sh
RUN chmod +x /usr/local/bin/generate-certs.sh \
    && /usr/local/bin/generate-certs.sh /certs

FROM owasp/modsecurity-crs:nginx-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/ /etc/nginx/conf.d/
COPY snippets/ /etc/nginx/snippets/
COPY html/ /etc/nginx/html/
COPY --from=cert-gen --chown=nginx:nginx /certs/ /etc/nginx/certs/

ENV PARANOIA=1
ENV ANOMALY_INBOUND=5
ENV ANOMALY_OUTBOUND=4
ENV REPORTING_LEVEL=2

EXPOSE 8080 8443

USER nginx
