\set ON_ERROR_STOP on

-- Migration users own their database and all objects created by TypeORM.
-- Runtime users are deliberately separate so least privilege can be enforced.
CREATE USER auth_migrator WITH PASSWORD :'AUTH_MIGRATOR_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER auth_service WITH PASSWORD :'AUTH_SERVICE_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER account_migrator WITH PASSWORD :'ACCOUNT_MIGRATOR_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER account_service WITH PASSWORD :'ACCOUNT_SERVICE_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER transaction_migrator WITH PASSWORD :'TRANSACTION_MIGRATOR_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER transaction_service WITH PASSWORD :'TRANSACTION_SERVICE_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER payment_migrator WITH PASSWORD :'PAYMENT_MIGRATOR_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER payment_service WITH PASSWORD :'PAYMENT_SERVICE_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER audit_migrator WITH PASSWORD :'AUDIT_MIGRATOR_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER audit_service WITH PASSWORD :'AUDIT_SERVICE_DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE;

CREATE DATABASE user_db OWNER auth_migrator;
CREATE DATABASE account_db OWNER account_migrator;
CREATE DATABASE transaction_db OWNER transaction_migrator;
CREATE DATABASE payment_db OWNER payment_migrator;
CREATE DATABASE audit_db OWNER audit_migrator;

REVOKE ALL ON DATABASE user_db FROM PUBLIC;
REVOKE ALL ON DATABASE account_db FROM PUBLIC;
REVOKE ALL ON DATABASE transaction_db FROM PUBLIC;
REVOKE ALL ON DATABASE payment_db FROM PUBLIC;
REVOKE ALL ON DATABASE audit_db FROM PUBLIC;

GRANT CONNECT ON DATABASE user_db TO auth_service;
GRANT CONNECT ON DATABASE account_db TO account_service;
GRANT CONNECT ON DATABASE transaction_db TO transaction_service;
GRANT CONNECT ON DATABASE payment_db TO payment_service;
GRANT CONNECT ON DATABASE audit_db TO audit_service;

\connect user_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO auth_service;
ALTER DEFAULT PRIVILEGES FOR ROLE auth_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_service;
ALTER DEFAULT PRIVILEGES FOR ROLE auth_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO auth_service;

\connect account_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO account_service;
ALTER DEFAULT PRIVILEGES FOR ROLE account_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO account_service;
ALTER DEFAULT PRIVILEGES FOR ROLE account_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO account_service;

\connect transaction_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO transaction_service;
ALTER DEFAULT PRIVILEGES FOR ROLE transaction_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO transaction_service;
ALTER DEFAULT PRIVILEGES FOR ROLE transaction_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO transaction_service;

\connect payment_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO payment_service;
ALTER DEFAULT PRIVILEGES FOR ROLE payment_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO payment_service;
ALTER DEFAULT PRIVILEGES FOR ROLE payment_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO payment_service;

\connect audit_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO audit_service;
ALTER DEFAULT PRIVILEGES FOR ROLE audit_migrator IN SCHEMA public
  GRANT SELECT, INSERT ON TABLES TO audit_service;
ALTER DEFAULT PRIVILEGES FOR ROLE audit_migrator IN SCHEMA public
  REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES FROM audit_service;
ALTER DEFAULT PRIVILEGES FOR ROLE audit_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO audit_service;
