#!/bin/sh
set -eu

psql \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set=ON_ERROR_STOP=1 \
  --set=AUTH_MIGRATOR_PASSWORD="$AUTH_MIGRATOR_PASSWORD" \
  --set=AUTH_SERVICE_DB_PASSWORD="$AUTH_SERVICE_DB_PASSWORD" \
  --set=ACCOUNT_MIGRATOR_PASSWORD="$ACCOUNT_MIGRATOR_PASSWORD" \
  --set=ACCOUNT_SERVICE_DB_PASSWORD="$ACCOUNT_SERVICE_DB_PASSWORD" \
  --set=TRANSACTION_MIGRATOR_PASSWORD="$TRANSACTION_MIGRATOR_PASSWORD" \
  --set=TRANSACTION_SERVICE_DB_PASSWORD="$TRANSACTION_SERVICE_DB_PASSWORD" \
  --set=PAYMENT_MIGRATOR_PASSWORD="$PAYMENT_MIGRATOR_PASSWORD" \
  --set=PAYMENT_SERVICE_DB_PASSWORD="$PAYMENT_SERVICE_DB_PASSWORD" \
  --set=AUDIT_MIGRATOR_PASSWORD="$AUDIT_MIGRATOR_PASSWORD" \
  --set=AUDIT_SERVICE_DB_PASSWORD="$AUDIT_SERVICE_DB_PASSWORD" \
  --file=/docker-entrypoint-templates/init.sql
