apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - staging-project.yaml
  - staging-runtime-project.yaml
  - staging-runtime-application.yaml
  - staging-application.yaml
