apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-bank-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault-bank-staging
    app.kubernetes.io/part-of: vault-bank
    environment: staging
  annotations:
    vault-bank.io/sync-state: enabled-phase5e-b4
spec:
  project: vault-bank-staging

  source:
    repoURL: https://github.com/sonappatil/vault_bank.git
    targetRevision: main
    path: gitops/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: vault-bank-staging

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PruneLast=true

  revisionHistoryLimit: 10
