apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-bank-runtime-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault-bank-runtime-staging
    app.kubernetes.io/part-of: vault-bank
    environment: staging
spec:
  project: vault-bank-runtime-staging

  source:
    repoURL: https://github.com/sonappatil/vault_bank.git
    targetRevision: main
    path: gitops/runtime/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: vault-bank-staging

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PruneLast=true

  revisionHistoryLimit: 10
