apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/name: vault-bank-staging
    app.kubernetes.io/part-of: vault-bank
    environment: staging
  name: vault-bank-staging
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  description: Restricted Vault Bank staging deployment
  destinations:
  - namespace: vault-bank-staging
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: ""
    kind: ConfigMap
  - group: ""
    kind: ResourceQuota
  - group: ""
    kind: Service
  - group: ""
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: batch
    kind: Job
  - group: networking.k8s.io
    kind: Ingress
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: traefik.io
    kind: Middleware
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/sonappatil/vault_bank.git
